FROM node:12

WORKDIR /app

RUN npm i cross-env -g

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm i

COPY ./src/ ./src/
RUN touch ./.env

CMD ["npm", "start"]