type Comment {
    id: ID!
    article: Article
    author: User
    body: String!
    createdAt: ISO8601DateTime!
    updatedAt: ISO8601DateTime!
}

input AddCommentInput {
    articleId: ID!
    body: String!
}

type AddCommentPayload {
    comment: Comment
    errors: [UserError!]!
}

input DeleteCommentInput {
    id: ID!
}

type DeleteCommentPayload {
    comment: Comment
}

type Query {
    articleComments(article: ID!): [Comment]
}

type Mutation {
    addComment(input: AddCommentInput!): AddCommentPayload @Auth(input: {required: true})
    deleteComment(input: DeleteCommentInput!): DeleteCommentPayload @Auth(input: {required: true})
}